import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Navbar } from '../components/Navbar';
import { Hero } from '../components/Hero';
import { Card } from '../components/Card';

export default function Home() {
  const restaurantData = [
    {
      city: 'Kota Bandung',
      rating: 4.5,
      title: 'Lorem Ipsum Dolor',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse volutpat ligula sapien, in tincidunt urna aliquam a. Cras in efficitur est, ultrices semper justo.',
      img: 'https://cdn.dribbble.com/users/250507/screenshots/13980835/media/a2d7c309e90872f866727f04b3f5a7ff.jpg?compress=1&resize=400x300'
    },
    {
      city: 'Kota Bandung',
      rating: 4.5,
      title: 'Lorem Ipsum Dolor',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse volutpat ligula sapien, in tincidunt urna aliquam a. Cras in efficitur est, ultrices semper justo.',
      img: 'https://cdn.dribbble.com/users/250507/screenshots/13980835/media/a2d7c309e90872f866727f04b3f5a7ff.jpg?compress=1&resize=400x300'
    },
    {
      city: 'Kota Bandung',
      rating: 4.5,
      title: 'Lorem Ipsum Dolor',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse volutpat ligula sapien, in tincidunt urna aliquam a. Cras in efficitur est, ultrices semper justo.',
      img: 'https://cdn.dribbble.com/users/250507/screenshots/13980835/media/a2d7c309e90872f866727f04b3f5a7ff.jpg?compress=1&resize=400x300'
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <Hero />
        <section>
          <h3>Explore Restaurant</h3>
          <div className={styles.cards}>
            {
              restaurantData.map((data, i) => (
                <Card key={i} city={data.city} rating={data.rating} title={data.title} body={data.body} img={data.img} />
              ))
            }
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <p>copyright @ 2020 - Hunger Apps</p>
      </footer>
    </div>
  )
}
